COMPONENT=SensingAppC
PFLAGS += -I/home/jiliac/Development/tinyos-main/tos/lib/net/tymo -I/home/jiliac/Development/tinyos-main/tos/lib/net/tymo/dymo -I/home/jiliac/Development/tinyos-main/tos/lib/net/tymo/mh
DOCDIR=~/tymo/web/html-doc/

TINYOS_ROOT_DIR?=/home/jiliac/Development/tinyos-main
include $(TINYOS_ROOT_DIR)/Makefile.include
